name: cortexwave-website
region: syd
domains:
  - domain: cortexwave.com.au
    type: PRIMARY
  - domain: www.cortexwave.com.au
    type: ALIAS
services:
  - name: cortexwave-web
    github:
      repo: stahir90/cortexwave-website
      branch: main
      deploy_on_push: true
    build_command: npm run build
    run_command: npm start
    environment_slug: node-js
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    envs:
      - key: MAILERSEND_API_TOKEN
        type: SECRET
      - key: MAILERSEND_FROM_EMAIL
        value: notifications@cortexwave.com.au
        type: GENERAL
      - key: MAILERSEND_FROM_NAME
        value: CortexWave
        type: GENERAL
      - key: MAILERSEND_TO_EMAIL
        value: tahirm.psn@gmail.com
        type: GENERAL
